baseURL = 'https://blog.nucieda.com'
languageCode = 'en-us'
title = 'Segmentation Fault'
theme = 'PaperMod'
ignoreFiles = ["content/posts/Templates/*"]

[params]
	author = "Nicolas Ucieda"
	email = "nicolas.ucieda@gmail.com"

	ShowReadingTime = true
	ShowBreadCrumbs = true
	ShowPostNavLinks = true
	ShowCodeCopyButtons = true
	ShowRssButtonInSectionTermList = true
